services:

# PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    env_file: .env
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sistema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  # Redis 
  redis:
    image: redis:7-alpine
    container_name: sistema_redis

    volumes:
      - redis_data:/data

    networks:
      - sistema_network

    restart: unless-stopped

# Spring Boot API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring_api   
    env_file: .env 
    environment:
      # Spring Config
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=${SERVER_PORT}
      
      # PostgreSQL Config
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      
      # JWT Config
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      
      # CORS Config
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS}   
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema_network 
    restart: unless-stopped

# Angular + Nginx

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sistema_web
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - sistema_network
    restart: unless-stopped

# Volumes

volumes:
  postgres_data:
    name: sistema_postgres_data
  redis_data:
    name: sistema_redis_data

# Network

networks:
  sistema_network:
    driver: bridge